
import React from 'react';

export const PrivacyPolicy: React.FC = () => {
  return (
    <div className="bg-white min-h-screen pt-40 pb-32 selection:bg-[#0085F7] selection:text-[#fff]">
      <div className="max-w-4xl mx-auto px-6">
        <div className="accent-bar bg-[#004b23] w-12 h-1.5 mb-10"></div>
        <span className="text-[10px] font-black uppercase tracking-[0.4em] text-gray-400 mb-6 block">Legal Protocol</span>
        <h1 className="text-5xl font-black uppercase tracking-tighter mb-16 text-[#1A1A1A]">
          Privacy <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#0085F7] to-[#00A94B]">Policy</span>
        </h1>
        
        <div className="space-y-16 text-gray-600 leading-relaxed font-normal text-lg">
          <section>
            <p className="text-sm text-gray-400 mb-8">Last updated: April 09, 2026</p>
            <p>At Antern, we value your privacy. This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p className="mt-4">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
          </section>

          <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Interpretation and Definitions</h2>
            <div className="space-y-8">
              <div>
                <h3 className="text-[#1A1A1A] font-bold mb-4 text-sm uppercase tracking-wider">Interpretation</h3>
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
              </div>
              <div>
                <h3 className="text-[#1A1A1A] font-bold mb-4 text-sm uppercase tracking-wider">Definitions</h3>
                <ul className="list-disc pl-6 space-y-4 text-[16px]">
                  <li><strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.</li>
                  <li><strong>Company:</strong> Refers to Antern, 10 M 226, 100 Ft Road, HRBR Layout, Block 1, Kalyan Nagar, Bangalore - 560043, Karnataka, India.</li>
                  <li><strong>Cookies:</strong> Small files placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                  <li><strong>Country:</strong> Karnataka, India.</li>
                  <li><strong>Device:</strong> Any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                  <li><strong>Personal Data:</strong> Any information that relates to an identified or identifiable individual.</li>
                  <li><strong>Service:</strong> Refers to the Website.</li>
                  <li><strong>Service Provider:</strong> Any natural or legal person who processes the data on behalf of the Company.</li>
                  <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                  <li><strong>Website:</strong> Refers to Antern, accessible from anterntech.com</li>
                  <li><strong>You:</strong> The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Collecting and Using Your Personal Data</h2>
            <div className="space-y-8">
              <div>
                <h3 className="text-[#1A1A1A] font-bold mb-4 text-sm uppercase tracking-wider">Types of Data Collected</h3>
                <p className="font-bold text-[#1A1A1A] mb-2">Personal Data</p>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className="list-disc pl-6 space-y-2 mt-4 text-[16px]">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Usage Data</li>
                </ul>
              </div>
              <div>
                <p className="font-bold text-[#1A1A1A] mb-2">Usage Data</p>
                <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device's IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Tracking Technologies and Cookies</h2>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
            <p className="mt-4">You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
          </section>

          <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-4 mt-6 text-[16px]">
              <li>Providing, maintaining, and improving our services</li>
              <li>Managing your registration and account</li>
              <li>Fulfilling contracts and transactions for our services</li>
              <li>Communicating with you by email, calls, SMS, or app notifications</li>
              <li>Providing you with relevant news, special offers, or information about our goods/services (unless you opt out)</li>
              <li>Handling your requests</li>
              <li>Security monitoring and service optimization</li>
              <li>Business transfers and analysis (including mergers/acquisitions, if applicable)</li>
              <li>Legal requirements and compliance</li>
            </ul>
            <p>Your data may also be used for analytics, trend analysis, marketing effectiveness, and overall experience improvements.</p>
          </section>

          <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Sharing Your Data</h2>
            <p>We may share your personal information in the following situations:</p>
            <ul className="list-disc pl-6 space-y-4 mt-6 text-[16px]">
             <li>With Service Providers (e.g. analytics, communication, and support tools)</li>
             <li>During business transfers, mergers, or asset sales, with prior notice</li>
             <li>With affiliates, under common control and subject to this Privacy Policy</li>
             <li>With business partners to offer products, services, or promotions</li>
             <li>With other users in public areas (such as forums or reviews)</li>
             <li>If required by law, government requests, or to protect company or public rights</li>
             <li>With your consent, for any other purposes you approve</li>
            </ul>
            <p>Your data may also be used for analytics, trend analysis, marketing effectiveness, and overall experience improvements.</p>
          </section>

          <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Retention of Your Data</h2>
            <p>We retain personal data only as long as necessary to fulfill the purposes outlined in this policy—including legal, analytical, security, and service improvement uses. Usage data is usually retained for a shorter period, except when needed for legal obligations or to improve platform security and functionality.</p>
          </section>
           <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Security of Your Data</h2>
            <p>We employ commercially acceptable security measures (including session controls and necessary cookies) to protect your information, but no online method is 100% secure. You can control cookie acceptance in your browser, but doing so may limit some service features.</p>
          </section>

           <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Links to Other Websites</h2>
            <p>Our service may contain links to external websites not operated by us. We advise reviewing each site's privacy policy; we are not responsible for the privacy practices of third parties.</p>
          </section>


           <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Changes to This Policy</h2>
            <p>We may update this Privacy Policy occasionally. Notice of changes will be posted here, and the revision date will be updated. Significant changes may be communicated via email or a prominent notice on our platform.</p>
          </section>

          <section>
            <h2 className="text-sm font-black uppercase tracking-[0.2em] text-[#004b23] mb-6 border-b border-gray-100 pb-4">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <div className="mt-8 bg-gray-50 p-8 border-l-4 border-[#0085F7]">
              <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2 font-black">Official Channels</p>
              <ul className="space-y-3">
                <li className="flex items-center gap-3">
                  <span className="text-[#1A1A1A] font-bold">Email:</span>
                  <a href="mailto:reach.anterntech@gmail.com" className="text-[#0085F7] hover:underline">info@anterntech.com</a>
                </li>
                <li className="flex items-start gap-3">
                  <span className="text-[#1A1A1A] font-bold">Address:</span>
                  <span className="text-gray-500 text-sm">10 M 226, 100 Ft Road, HRBR Layout, Block 1, Kalyan Nagar, Bangalore - 560043, Karnataka, India</span>
                </li>
              </ul>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};
